config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: "production"
  enable_pe_plans: true
pipelines:
  putty390:
    triggers:
    - "COMMIT"
    stages:
    - name: "Impact Analysis stage"
      steps:
      - type: "IMPACT_ANALYSIS"
        concurrent_compilations: 10
        all_deployments: true
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
    - name: "Deployment stage"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to development on github"
        policy:
          name: "cd4pe_deployments::direct"
        parameters:
          noop: false
          fail_if_no_nodes: true
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "github"
        target:
          type: "NODE_GROUP"
          node_group_id: "c5ad4792-12a5-4cd9-9a2a-ea3d07d384b9"
      auto_promote: false
  master:
    triggers:
    - "COMMIT"
    stages:
    - name: "Code Validation stage"
      steps:
      - type: "JOB"
        name: "control-repo-manifest-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-hiera-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      - type: "JOB"
        name: "control-repo-template-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
    - name: "Impact Analysis stage"
      steps:
      - type: "IMPACT_ANALYSIS"
        concurrent_compilations: 10
        all_deployments: true
      - type: "PULL_REQUEST_GATE"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
spec_version: "V1"
