config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: "production"
pipelines:
  cdpe_2795_tests_staging:
    triggers:
    - "COMMIT"
    stages:
    - name: "Pipeline Stage 1"
      steps:
      - type: "IMPACT_ANALYSIS"
        concurrent_compilations: 10
        all_deployments: true
        impact_analysis_hiera_regex: '^doesnotexist$'
      auto_promote: false
    - name: "Pipeline Stage 2"
      steps:
      - type: "DEPLOYMENT"
        name: "Deployment to impact_analysis_tests_prod on pe-github"
        policy:
          name: "cd4pe_deployments::eventual_consistency"
        timeout: 3600000
        concurrent_compilations: 0
        all_deployments: false
        pe_server: "pe-github"
        target:
          type: "NODE_GROUP"
          node_group_id: "250fd263-8456-4114-b559-9c6d9fa27748"
      auto_promote: false
spec_version: "V1"
