config:
  enable_pull_requests_from_forks: false
  deployment_policy_branch: "pac-3.2.0-test-2"
pipelines:
  pac-3.2.0-test-2:
    triggers:
    - "COMMIT"
    stages:
    - name: "Pipeline Stage 1"
      steps:
      - type: "JOB"
        name: "control-repo-puppetfile-syntax-validate"
        concurrent_compilations: 0
        all_deployments: false
      auto_promote: false
spec_version: "V1"
